[package]
name = "mps-core"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mps-formula = { path = "../mps-formula" }
rapier3d = { workspace = true }
parking_lot = { workspace = true }
hashbrown = { workspace = true }
smallvec = { workspace = true }
rayon = { workspace = true }
anvilkit = { workspace = true, optional = true }
bevy_ecs = { workspace = true, optional = true }
dashmap = { workspace = true }
mps-bindgen-macro = { path = "../mps-bindgen-macro" }

[features]
default = []
anvilkit-bridge = ["dep:anvilkit", "dep:bevy_ecs"]
relative-force = []
profiler = ["rapier3d/profiler"]

[build-dependencies]
cbindgen = "0.29.4"
mps-build-common = { path = "../mps-build-common" }
