// Auto-generated by `cargo run -p xtask -- dump-metrics`.
// Do NOT edit by hand — re-run the command above after large changes
// (OPTIMIZATION.md §N3).
//
// Source of truth:
//   TEST_COUNT       = `grep -rh '#[test]' crates/mps-test/src/ | wc -l`
//   JNI_METHOD_COUNT= `grep -cE 'jni!\\(|jni_e_c!\\(' crates/mps-jni/src/lib.rs`
//   CORE_FFI_COUNT  = `grep -rhE '^pub extern "C"' crates/mps-core/src/rapier/ | wc -l`
//   VERSION         = workspace `version` in root Cargo.toml
//   FORMULA_MODULE_COUNT / CELESTIAL_COUNT / GRAVITY_MODEL_COUNT / INTEGRATOR_COUNT
//                 = module / enum counts derived from source
//   FFI_WORLD / FFI_RIGID_BODY / FFI_COLLIDER / FFI_QUERY
//                 = `pub extern "C" fn <prefix>_*` in crates/mps-core/src/rapier
/// Workspace version (from root Cargo.toml), for the footer / brand.
pub const VERSION: &str = "0.1.4";
/// Total number of `#[test]` items in `mps-test`.
pub const TEST_COUNT: &str = "1142";
/// Total number of `jni!(`/`jni_e_c!(` method entries in `mps-jni`.
pub const JNI_METHOD_COUNT: &str = "601";
/// Total number of `pub extern "C" fn` declarations in `mps-core/rapier`.
pub const CORE_FFI_COUNT: &str = "892";
/// Number of `pub mod` formula submodules under mps-formula scientists+disciplines.
pub const FORMULA_MODULE_COUNT: &str = "147";
/// Number of `CelestialBodyId` variants (built-in celestial bodies).
pub const CELESTIAL_COUNT: &str = "10";
/// Number of `pub mod` gravity model submodules under mps-core/src/gravity.
pub const GRAVITY_MODEL_COUNT: &str = "4";
/// Number of `OrbitIntegration` variants (integrator selection).
pub const INTEGRATOR_COUNT: &str = "6";
/// `pub extern "C" fn world_*` declarations in mps-core/rapier.
pub const FFI_WORLD: &str = "118";
/// `pub extern "C" fn rigid_body_*` declarations in mps-core/rapier.
pub const FFI_RIGID_BODY: &str = "64";
/// `pub extern "C" fn collider_*` declarations in mps-core/rapier.
pub const FFI_COLLIDER: &str = "79";
/// `pub extern "C" fn query_*` declarations in mps-core/rapier.
pub const FFI_QUERY: &str = "58";
/// `pub extern "C" fn soft_body_*` declarations in mps-core/rapier.
pub const FFI_SOFT_BODY: &str = "87";
/// `pub extern "C" fn disaster_*` declarations in mps-core/rapier.
pub const FFI_DISASTER: &str = "9";
/// `pub extern "C" fn volcano_*` declarations in mps-core/rapier.
pub const FFI_VOLCANO: &str = "9";
/// `jni!` entries with a `softBody*` method name in mps-jni.
pub const JNI_SOFT_BODY: &str = "87";
/// `#[test]` functions whose name contains `soft_body` in mps-test.
pub const TEST_SOFT_BODY: &str = "90";
/// Number of natural satellites (moons) in `mps-formula::celestial_data::MOONS`.
pub const MOON_COUNT: &str = "30";
