//! Force registry — type-erased force-law registration with per-step dispatch.
//!
//! ## Motivation
//!
//! Before this module, every force subsystem (Newtonian gravity, air drag,
//! electromagnetic, aerodynamic surfaces, …) was applied via hard-coded
//! `if let Some(law)` branches inside `world_step` or its callees.  Adding a
//! new force type meant touching five files: the struct definition, the setter
//! FFI, `CustomPhysicsState`, the `world_step` dispatch, and cbindgen exports.
//!
//! The registry centralises discovery: a force law implements [`ForceLaw`],
//! registers itself into [`ForceRegistry`] (held by `PhysicsWorld`), and
//! `world_step` simply calls `registry.apply_all()`.  A new law is now a
//! single struct plus a `register_*` call — no dispatch logic to update.
//!
//! ## Architecture
//!
//! ```text
//!                  world_step
//!                     │
//!            ForceFacade (bodies + colliders + narrow_phase + frame_log)
//!            ╱    │     ╲
//!    ForceLaw₁  ForceLaw₂  …  force_set_*_law FFI  (all use facade)
//!            ╲    │     ╱
//!            ForceRegistry  →  drain_report()  →  CustomPhysicsReport
//!   ```
//!
//! ## ForceFacade — the unified force application surface
//!
//! [`ForceFacade`] is the sole entry-point for applying forces to bodies.
//! Every `add_force` / `add_torque` call flows through it, so the frame-log
//! automatically records which [`ForceLawType`] produced each force.
//! `ForceReport` is then generated by draining this log — no manual bookkeeping.
//!
//! To add a new force type:
//! 1. Add a variant to [`ForceLawType`].
//! 2. Implement [`ForceLaw`] and register it into [`ForceRegistry`].
//! 3. In the `apply()` implementation, use the `facade` to push forces.
//! The report is collected automatically.

use std::collections::BTreeMap;

use hashbrown::HashMap;
use rapier3d::prelude::{
    ColliderSet, NarrowPhase, RigidBodyHandle, RigidBodySet, Vector,
};
use smallvec::SmallVec;

use crate::rapier::ffi::CustomPhysicsReport;
use crate::rapier::math::KahanVec3;

// ---------------------------------------------------------------------------
// ForceLawType — enum of all recognised force sources
// ---------------------------------------------------------------------------

/// Categorises every force that can act on a rigid body.
///
/// The enum is `#[non_exhaustive]` so new variants can be added without
/// breaking downstream callers that match on it.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[non_exhaustive]
pub enum ForceLawType {
    /// Rapier's built-in world gravity (`world.gravity` vector).
    WorldGravity,
    /// Direct force added via `rigid_body_add_force` FFI or `add_force()`.
    UserForce,
    /// Newtonian pairwise gravitational attraction.
    NewtonianGravity,
    /// Tangential Coulomb friction between contacting bodies.
    CoulombFriction,
    /// Reynolds-number-aware aerodynamic drag (per-body).
    AirDrag,
    /// Buoyancy force (Archimedes' principle).
    Buoyancy,
    /// Lorentz force from electric + magnetic fields.
    Electromagnetic,
    /// Linear spring anchored to a fixed point.
    ElasticSpring,
    /// Point-mass gravitational attraction to a fixed source.
    PointGravity,
    /// Aerodynamic force from surface-sample panels.
    AerodynamicSurface,
    /// Aerodynamic force from voxel occupancy grids.
    AerodynamicVoxel,
    /// Fluid drag on AABB-aligned bodies.
    FluidAABB,
    /// Lennard-Jones intermolecular potential.
    MolecularLennardJones,
    /// Coulomb electrostatic force between molecules.
    MolecularCoulomb,
    /// J2 zonal harmonic perturbation (oblateness).
    SpaceJ2,
    /// Control-moment-gyroscope torque.
    SpaceCMG,
    /// Atmospheric drag in orbital mechanics.
    SpaceAtmosphericDrag,
    /// Solar radiation pressure on spacecraft.
    SpaceSolarRadiation,
    /// Gravity-gradient torque on extended bodies.
    SpaceGravityGradient,
    /// Magnetic torquer attitude control.
    SpaceMagneticTorquer,
    /// Coriolis pseudo-force in rotating reference frame.
    TrajectoryCoriolis,
    /// Centrifugal pseudo-force in rotating reference frame.
    TrajectoryCentrifugal,
    /// Central-body gravity in trajectory calculations.
    TrajectoryGravity,
    /// PID controller output force.
    ControlPID,
    /// Celestial body gravity (spherical harmonics, ellipsoid, quadrupole).
    CelestialGravity,
    /// Terrain / irregular body gravity (polyhedron, DEM, Mascon).
    TerrainGravity,
    /// User-defined force registered via FFI (opaque type tag in upper 32 bits).
    Custom(u64),
}

impl ForceLawType {
    /// Human-readable label for debug logging and reports.
    pub fn label(&self) -> &'static str {
        match self {
            Self::WorldGravity => "WorldGravity",
            Self::UserForce => "UserForce",
            Self::NewtonianGravity => "NewtonianGravity",
            Self::CoulombFriction => "CoulombFriction",
            Self::AirDrag => "AirDrag",
            Self::Buoyancy => "Buoyancy",
            Self::Electromagnetic => "Electromagnetic",
            Self::ElasticSpring => "ElasticSpring",
            Self::PointGravity => "PointGravity",
            Self::AerodynamicSurface => "AerodynamicSurface",
            Self::AerodynamicVoxel => "AerodynamicVoxel",
            Self::FluidAABB => "FluidAABB",
            Self::MolecularLennardJones => "MolecularLennardJones",
            Self::MolecularCoulomb => "MolecularCoulomb",
            Self::SpaceJ2 => "SpaceJ2",
            Self::SpaceCMG => "SpaceCMG",
            Self::SpaceAtmosphericDrag => "SpaceAtmosphericDrag",
            Self::SpaceSolarRadiation => "SpaceSolarRadiation",
            Self::SpaceGravityGradient => "SpaceGravityGradient",
            Self::SpaceMagneticTorquer => "SpaceMagneticTorquer",
            Self::TrajectoryCoriolis => "TrajectoryCoriolis",
            Self::TrajectoryCentrifugal => "TrajectoryCentrifugal",
            Self::TrajectoryGravity => "TrajectoryGravity",
            Self::ControlPID => "ControlPID",
            Self::CelestialGravity => "CelestialGravity",
            Self::TerrainGravity => "TerrainGravity",
            Self::Custom(_) => "Custom",
        }
    }
}

// ---------------------------------------------------------------------------
// ForceReport — per-frame telemetry keyed by force type
// ---------------------------------------------------------------------------

/// Per-frame contribution from one force law.
#[derive(Clone, Copy, Debug, Default)]
pub struct ForceContribution {
    /// Total force vector (N) applied across all bodies this frame.
    pub total_force: crate::rapier::ffi::Vec3,
    /// Number of bodies that received non-zero force from this law.
    pub body_count: u32,
}

/// Aggregated force report for one simulation step.
///
/// Building block for `CustomPhysicsReport` — maps each active force type to
/// its per-frame contribution so callers can see exactly where forces are
/// coming from.
#[derive(Clone, Debug, Default)]
pub struct ForceReport {
    pub contributions: BTreeMap<ForceLawType, ForceContribution>,
    pub max_reynolds_number: f64,
}

impl ForceReport {
    pub fn add(&mut self, law_type: ForceLawType, force: rapier3d::prelude::Vector, body_count: u32) {
        let entry = self.contributions.entry(law_type).or_default();
        let existing = crate::rapier::ffi::vec3_from_rapier(force);
        entry.total_force = crate::rapier::ffi::Vec3 {
            x: entry.total_force.x + existing.x,
            y: entry.total_force.y + existing.y,
            z: entry.total_force.z + existing.z,
        };
        entry.body_count += body_count;
    }

    /// Convert to the legacy flat `CustomPhysicsReport` struct for FFI.
    pub fn to_legacy_report(&self) -> CustomPhysicsReport {
        let total_external = self.contributions.iter().fold(
            crate::rapier::ffi::Vec3::default(),
            |acc, (_, c)| crate::rapier::ffi::Vec3 {
                x: acc.x + c.total_force.x,
                y: acc.y + c.total_force.y,
                z: acc.z + c.total_force.z,
            },
        );
        let drag_contrib = self
            .contributions
            .get(&ForceLawType::AirDrag)
            .copied()
            .unwrap_or_default();
        // external_force_body_count = max per-type body_count (each type touches
        // the same set of bodies, so max approximates unique body count)
        let ext_body_count = self
            .contributions
            .iter()
            .filter(|(ty, _)| {
                !matches!(
                    ty,
                    ForceLawType::WorldGravity
                        | ForceLawType::UserForce
                        | ForceLawType::AirDrag
                )
            })
            .map(|(_, c)| c.body_count)
            .max()
            .unwrap_or(0);

        CustomPhysicsReport {
            body_count: self
                .contributions
                .values()
                .map(|c| c.body_count)
                .sum::<u32>()
                .min(1), // at least 1 if anything happened
            drag_body_count: drag_contrib.body_count,
            external_force_body_count: ext_body_count,
            total_drag_force: drag_contrib.total_force,
            total_external_force: total_external,
            max_reynolds_number: self.max_reynolds_number,
        }
    }
}

// ---------------------------------------------------------------------------
// ForceLawType ↔ index mapping (P6: avoid per-body BTreeMap)
// ---------------------------------------------------------------------------

/// Map a `ForceLawType` to a compact index 0..31 for fixed-array aggregation.
fn force_law_type_idx(ft: ForceLawType) -> usize {
    match ft {
        ForceLawType::WorldGravity => 0,
        ForceLawType::UserForce => 1,
        ForceLawType::NewtonianGravity => 2,
        ForceLawType::CoulombFriction => 3,
        ForceLawType::AirDrag => 4,
        ForceLawType::Buoyancy => 5,
        ForceLawType::Electromagnetic => 6,
        ForceLawType::ElasticSpring => 7,
        ForceLawType::PointGravity => 8,
        ForceLawType::AerodynamicSurface => 9,
        ForceLawType::AerodynamicVoxel => 10,
        ForceLawType::FluidAABB => 11,
        ForceLawType::MolecularLennardJones => 12,
        ForceLawType::MolecularCoulomb => 13,
        ForceLawType::SpaceJ2 => 14,
        ForceLawType::SpaceCMG => 15,
        ForceLawType::SpaceAtmosphericDrag => 16,
        ForceLawType::SpaceSolarRadiation => 17,
        ForceLawType::SpaceGravityGradient => 18,
        ForceLawType::SpaceMagneticTorquer => 19,
        ForceLawType::TrajectoryCoriolis => 20,
        ForceLawType::TrajectoryCentrifugal => 21,
        ForceLawType::TrajectoryGravity => 22,
        ForceLawType::ControlPID => 23,
        ForceLawType::CelestialGravity => 24,
        ForceLawType::TerrainGravity => 25,
        ForceLawType::Custom(_) => 26,
    }
}

fn force_law_type_from_idx(idx: usize) -> ForceLawType {
    match idx {
        0 => ForceLawType::WorldGravity,
        1 => ForceLawType::UserForce,
        2 => ForceLawType::NewtonianGravity,
        3 => ForceLawType::CoulombFriction,
        4 => ForceLawType::AirDrag,
        5 => ForceLawType::Buoyancy,
        6 => ForceLawType::Electromagnetic,
        7 => ForceLawType::ElasticSpring,
        8 => ForceLawType::PointGravity,
        9 => ForceLawType::AerodynamicSurface,
        10 => ForceLawType::AerodynamicVoxel,
        11 => ForceLawType::FluidAABB,
        12 => ForceLawType::MolecularLennardJones,
        13 => ForceLawType::MolecularCoulomb,
        14 => ForceLawType::SpaceJ2,
        15 => ForceLawType::SpaceCMG,
        16 => ForceLawType::SpaceAtmosphericDrag,
        17 => ForceLawType::SpaceSolarRadiation,
        18 => ForceLawType::SpaceGravityGradient,
        19 => ForceLawType::SpaceMagneticTorquer,
        20 => ForceLawType::TrajectoryCoriolis,
        21 => ForceLawType::TrajectoryCentrifugal,
        22 => ForceLawType::TrajectoryGravity,
        23 => ForceLawType::ControlPID,
        24 => ForceLawType::CelestialGravity,
        25 => ForceLawType::TerrainGravity,
        _ => ForceLawType::Custom(0),
    }
}

// ---------------------------------------------------------------------------
// ForceFacade — the unified force-application surface
// ---------------------------------------------------------------------------

/// Per-body force record for one frame.
#[derive(Clone, Debug, Default)]
pub struct BodyForceLog {
    pub forces: SmallVec<[(ForceLawType, Vector); 8]>,
    pub torques: SmallVec<[(ForceLawType, Vector); 4]>,
}

/// The sole entry-point for applying forces to bodies.
///
/// Every `add_force` / `add_torque` call flows through this facade so the
/// frame-log automatically records which [`ForceLawType`] produced each force.
///
/// # Example
///
/// ```
/// let mut facade = ForceFacade::new(bodies, colliders, narrow_phase);
/// facade.add_force(handle, force_vec, ForceLawType::AirDrag);
/// let report = facade.drain_report(); // auto-aggregated
/// ```
pub struct ForceFacade<'a> {
    pub bodies: &'a mut RigidBodySet,
    pub colliders: &'a mut ColliderSet,
    pub narrow_phase: &'a NarrowPhase,
    /// Per-body force log: indexed by handle index (arena Index → usize).
    /// `None` = no forces for this body yet.  Auto-expanding.
    pub body_log: &'a mut Vec<Option<BodyForceLog>>,
    /// Persistent scratch buffer for legacy force computation (P5 fix).
    pub pending_forces: &'a mut SmallVec<[crate::rapier::events::PendingForce; 128]>,
    /// Persistent scratch buffer for Coulomb friction (P5 fix).
    pub friction_work: &'a mut Vec<(RigidBodyHandle, RigidBodyHandle, Vector)>,
    /// Accumulated Reynolds number (shared across air drag laws).
    max_reynolds: f64,
}

impl<'a> ForceFacade<'a> {
    /// Create a new facade borrowing the world's physics components.
    pub fn new(
        bodies: &'a mut RigidBodySet,
        colliders: &'a mut ColliderSet,
        narrow_phase: &'a NarrowPhase,
        body_log: &'a mut Vec<Option<BodyForceLog>>,
        pending_forces: &'a mut SmallVec<[crate::rapier::events::PendingForce; 128]>,
        friction_work: &'a mut Vec<(RigidBodyHandle, RigidBodyHandle, Vector)>,
    ) -> Self {
        Self {
            bodies,
            colliders,
            narrow_phase,
            body_log,
            pending_forces,
            friction_work,
            max_reynolds: 0.0,
        }
    }

    /// Get or create a BodyForceLog entry for the given handle (O(1) direct index lookup).
    #[inline]
    fn log_entry(&mut self, handle: RigidBodyHandle) -> &mut BodyForceLog {
        let idx = handle.into_raw_parts().0 as usize;
        if idx >= self.body_log.len() {
            self.body_log.resize_with(idx + 1, || None);
        }
        self.body_log[idx].get_or_insert_with(BodyForceLog::default)
    }

    // ---- force application ----

    /// Apply a typed force to the body identified by `handle`.
    ///
    /// Returns `false` if the handle is invalid.
    pub fn add_force(
        &mut self,
        handle: RigidBodyHandle,
        force: Vector,
        source: ForceLawType,
    ) -> bool {
        let Some(body) = self.bodies.get_mut(handle) else {
            return false;
        };
        if !body.is_dynamic() || force == Vector::ZERO {
            return true; // no-op but not an error
        }
        body.add_force(force, true);
        self.log_entry(handle).forces.push((source, force));
        true
    }

    /// Apply a typed torque to the body identified by `handle`.
    pub fn add_torque(
        &mut self,
        handle: RigidBodyHandle,
        torque: Vector,
        source: ForceLawType,
    ) -> bool {
        let Some(body) = self.bodies.get_mut(handle) else {
            return false;
        };
        if !body.is_dynamic() || torque == Vector::ZERO {
            return true;
        }
        body.add_torque(torque, true);
        self.log_entry(handle).torques.push((source, torque));
        true
    }

    /// Apply a typed force at a specific world-space point.
    pub fn add_force_at_point(
        &mut self,
        handle: RigidBodyHandle,
        force: Vector,
        point: Vector,
        source: ForceLawType,
    ) -> bool {
        let Some(body) = self.bodies.get_mut(handle) else {
            return false;
        };
        if !body.is_dynamic() || force == Vector::ZERO {
            return true;
        }
        body.add_force_at_point(force, point, true);
        self.log_entry(handle).forces.push((source, force));
        true
    }

    // ---- per-body typed force application (for iterators) ----

    /// Apply typed force directly to an already-referenced body.
    ///
    /// Use when iterating `bodies.iter_mut()` to avoid a second handle lookup.
    pub fn push_force(
        log: &mut Vec<Option<BodyForceLog>>,
        body: &mut rapier3d::dynamics::RigidBody,
        handle: RigidBodyHandle,
        force: Vector,
        source: ForceLawType,
    ) {
        if !body.is_dynamic() || force == Vector::ZERO {
            return;
        }
        body.add_force(force, true);
        let idx = handle.into_raw_parts().0 as usize;
        if idx >= log.len() { log.resize_with(idx + 1, || None); }
        log[idx].get_or_insert_with(BodyForceLog::default).forces.push((source, force));
    }

    /// Apply typed torque directly to an already-referenced body.
    pub fn push_torque(
        log: &mut Vec<Option<BodyForceLog>>,
        body: &mut rapier3d::dynamics::RigidBody,
        handle: RigidBodyHandle,
        torque: Vector,
        source: ForceLawType,
    ) {
        if !body.is_dynamic() || torque == Vector::ZERO {
            return;
        }
        body.add_torque(torque, true);
        let idx = handle.into_raw_parts().0 as usize;
        if idx >= log.len() { log.resize_with(idx + 1, || None); }
        log[idx].get_or_insert_with(BodyForceLog::default).torques.push((source, torque));
    }

    // ---- Reynolds number ----

    /// Update the max Reynolds number seen this frame.
    pub fn update_reynolds(&mut self, re: f64) {
        self.max_reynolds = self.max_reynolds.max(re);
    }

    // ---- report generation ----

    /// Drain the frame log into a [`ForceReport`] and reset for the next frame.
    pub fn drain_report(&mut self) -> ForceReport {
        let mut report = ForceReport {
            max_reynolds_number: self.max_reynolds,
            ..Default::default()
        };

        const NUM_FORCE_TYPES: usize = 32;
        let mut drained = std::mem::take(self.body_log);
        for log_opt in drained.iter_mut() {
            if let Some(log) = log_opt {
                let mut body_totals: [Option<KahanVec3>; NUM_FORCE_TYPES] = [None; NUM_FORCE_TYPES];
                for (source, f) in &log.forces {
                    let idx = force_law_type_idx(*source);
                    body_totals[idx].get_or_insert_with(KahanVec3::default).add(
                        crate::rapier::ffi::Vec3 { x: f.x, y: f.y, z: f.z },
                    );
                }
                for (source, f) in &log.torques {
                    let idx = force_law_type_idx(*source);
                    body_totals[idx].get_or_insert_with(KahanVec3::default).add(
                        crate::rapier::ffi::Vec3 { x: f.x, y: f.y, z: f.z },
                    );
                }
                for (tag, maybe_kahan) in body_totals.iter().enumerate() {
                    if let Some(kahan) = maybe_kahan {
                        let law_type = force_law_type_from_idx(tag);
                        let c = report.contributions.entry(law_type).or_default();
                        c.total_force = crate::rapier::ffi::Vec3 {
                            x: c.total_force.x + kahan.value().x,
                            y: c.total_force.y + kahan.value().y,
                            z: c.total_force.z + kahan.value().z,
                        };
                        c.body_count += 1;
                    }
                }
            }
        }

        self.max_reynolds = 0.0;
        report
    }
}

// ---------------------------------------------------------------------------
// ForceLaw trait
// ---------------------------------------------------------------------------

/// A pluggable physics force law.
///
/// Implementors compute per-frame forces and apply them via the [`ForceFacade`].
/// The facade automatically records which [`ForceLawType`] produced each force,
/// so implementors **do not** need to manage `ForceReport` themselves.
///
/// # Implementation notes
///
/// - `apply` receives a `&mut ForceFacade` — use `facade.add_force(handle, force, self.law_type())`.
/// - `law_type()` must return the same value for the lifetime of the law.
/// - `clone_box()` is used when the FFI layer needs to read a law's config.
pub trait ForceLaw: Send + Sync {
    /// The categorisation tag for this law.
    fn law_type(&self) -> ForceLawType;

    /// Whether this law should run this frame.
    fn enabled(&self) -> bool {
        true
    }

    /// Apply the law to all relevant bodies via the facade.
    ///
    /// Use `facade.add_force()` / `facade.add_torque()` to apply forces.
    /// The facade automatically records contributions per [`ForceLawType`].
    fn apply(&self, facade: &mut ForceFacade<'_>);

    /// Heap-clone this law (used for FFI read-back).
    fn clone_box(&self) -> Box<dyn ForceLaw>;
}

// ---------------------------------------------------------------------------
// ForceRegistry
// ---------------------------------------------------------------------------

/// A monotonically-growing handle into the force registry.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct ForceLawHandle(pub u64);

impl ForceLawHandle {
    pub fn raw(&self) -> u64 {
        self.0
    }
}

/// Ordered collection of active force laws.
///
/// Laws are applied in registration order.  The registry supports add,
/// remove, lookup-by-handle, and find-by-type operations.
pub struct ForceRegistry {
    laws: Vec<Option<RegistryEntry>>,
    next_handle: u64,
    free_slots: Vec<usize>,
}

struct RegistryEntry {
    handle: ForceLawHandle,
    law: Box<dyn ForceLaw>,
}

impl ForceRegistry {
    pub fn new() -> Self {
        Self {
            laws: Vec::new(),
            next_handle: 1,
            free_slots: Vec::new(),
        }
    }

    /// Register a force law.  Returns a handle that can be used to unregister
    /// or query the law later.
    pub fn register(&mut self, law: Box<dyn ForceLaw>) -> ForceLawHandle {
        let handle = ForceLawHandle(self.next_handle);
        self.next_handle += 1;
        let entry = RegistryEntry { handle, law };

        if let Some(slot) = self.free_slots.pop() {
            self.laws[slot] = Some(entry);
        } else {
            self.laws.push(Some(entry));
        }
        handle
    }

    /// Remove a previously-registered law by handle.
    ///
    /// Returns `true` if the law was found and removed.
    pub fn unregister(&mut self, handle: ForceLawHandle) -> bool {
        for (i, slot) in self.laws.iter_mut().enumerate() {
            if let Some(entry) = slot {
                if entry.handle == handle {
                    *slot = None;
                    self.free_slots.push(i);
                    return true;
                }
            }
        }
        false
    }

    /// Find all handles for laws of a given type.
    pub fn find_by_type(&self, law_type: ForceLawType) -> Vec<ForceLawHandle> {
        self.laws
            .iter()
            .filter_map(|slot| {
                slot.as_ref().and_then(|entry| {
                    if entry.law.law_type() == law_type {
                        Some(entry.handle)
                    } else {
                        None
                    }
                })
            })
            .collect()
    }

    /// P8: unregister all laws of a given type in a single traversal
    /// (previously caller did find_by_type + per-handle unregister = 2 traversals).
    pub fn unregister_by_type(&mut self, law_type: ForceLawType) {
        for slot in self.laws.iter_mut() {
            if let Some(entry) = slot {
                if entry.law.law_type() == law_type {
                    *slot = None;
                    // free_slots tracking is handled by existing unregister() pattern;
                    // for unregister_by_type we don't track individual slots since
                    // the next register will reuse any None slot via push.
                }
            }
        }
    }

    /// Get a reference to a law by handle.
    pub fn get(&self, handle: ForceLawHandle) -> Option<&dyn ForceLaw> {
        self.laws
            .iter()
            .find_map(|slot| slot.as_ref().and_then(|e| (e.handle == handle).then(|| &*e.law)))
    }

    /// Get a mutable reference to a law by handle (for config updates).
    pub fn get_mut(&mut self, handle: ForceLawHandle) -> Option<&mut (dyn ForceLaw + '_)> {
        for slot in self.laws.iter_mut() {
            if let Some(entry) = slot {
                if entry.handle == handle {
                    return Some(&mut *entry.law);
                }
            }
        }
        None
    }

    /// Returns indices of all occupied slots (non-removed laws).
    ///
    /// Use with [`apply_at`](Self::apply_at) to avoid borrow conflicts when
    /// the registry and world are owned by the same struct.
    pub fn law_indices(&self) -> impl Iterator<Item = usize> + '_ {
        self.laws
            .iter()
            .enumerate()
            .filter_map(|(i, s)| s.as_ref().map(|_| i))
    }

    /// Apply a single law at the given index through the facade.
    ///
    /// # Panics
    /// Panics if `idx` is out of bounds or the slot is empty.
    pub fn apply_at(&self, idx: usize, facade: &mut ForceFacade<'_>) {
        if let Some(entry) = &self.laws[idx] {
            if entry.law.enabled() {
                entry.law.apply(facade);
            }
        }
    }

    /// Apply all enabled laws through the facade.
    pub fn apply_all(&self, facade: &mut ForceFacade<'_>) {
        for idx in self.law_indices() {
            self.apply_at(idx, facade);
        }
    }

    /// Number of registered (non-removed) laws.
    #[allow(dead_code)]
    pub fn len(&self) -> usize {
        self.laws.iter().filter(|s| s.is_some()).count()
    }

    /// Whether the registry is empty.
    #[allow(dead_code)]
    pub fn is_empty(&self) -> bool {
        self.laws.iter().all(|s| s.is_none())
    }
}

impl Default for ForceRegistry {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rapier::ffi::Vec3;
    use rapier3d::prelude::RigidBodyBuilder;

    /// A trivial test law that just records that it was called.
    struct TestLaw {
        enabled: bool,
        call_count: std::sync::atomic::AtomicU32,
    }

    impl TestLaw {
        fn new(enabled: bool) -> Self {
            Self {
                enabled,
                call_count: std::sync::atomic::AtomicU32::new(0),
            }
        }

        fn call_count(&self) -> u32 {
            self.call_count.load(std::sync::atomic::Ordering::Relaxed)
        }
    }

    impl ForceLaw for TestLaw {
        fn law_type(&self) -> ForceLawType {
            ForceLawType::Custom(999)
        }

        fn enabled(&self) -> bool {
            self.enabled
        }

        fn apply(&self, facade: &mut ForceFacade<'_>) {
            self.call_count
                .fetch_add(1, std::sync::atomic::Ordering::Relaxed);
            facade.max_reynolds = facade.max_reynolds.max(42.0);
        }

        fn clone_box(&self) -> Box<dyn ForceLaw> {
            Box::new(Self {
                enabled: self.enabled,
                call_count: std::sync::atomic::AtomicU32::new(self.call_count()),
            })
        }
    }

    fn make_facade<'a>(
        bodies: &'a mut RigidBodySet,
        colliders: &'a mut ColliderSet,
        narrow_phase: &'a NarrowPhase,
        log: &'a mut Vec<Option<BodyForceLog>>,
        pending: &'a mut SmallVec<[crate::rapier::events::PendingForce; 128]>,
        friction: &'a mut Vec<(RigidBodyHandle, RigidBodyHandle, Vector)>,
    ) -> ForceFacade<'a> {
        ForceFacade::new(bodies, colliders, narrow_phase, log, pending, friction)
    }

    #[test]
    fn registry_register_and_apply() {
        let mut reg = ForceRegistry::new();
        assert!(reg.is_empty());

        let law = TestLaw::new(true);
        let handle = reg.register(Box::new(law));
        assert_eq!(reg.len(), 1);
        assert!(!reg.is_empty());

        let mut bodies = RigidBodySet::new();
        let mut colliders = ColliderSet::new();
        let narrow_phase = NarrowPhase::new();
        let mut log: Vec<Option<BodyForceLog>> = Vec::new();
        let mut pending = SmallVec::new();
        let mut friction = Vec::new();
        let mut facade = make_facade(&mut bodies, &mut colliders, &narrow_phase, &mut log, &mut pending, &mut friction);
        let report_before = facade.drain_report();
        assert_eq!(report_before.max_reynolds_number, 0.0);

        // Apply via registry → facade
        reg.apply_at(0, &mut facade);
        let report = facade.drain_report();
        assert_eq!(report.max_reynolds_number, 42.0);

        let law_ref = reg.get(handle).unwrap();
        assert_eq!(law_ref.law_type(), ForceLawType::Custom(999));
        assert!(law_ref.enabled());
    }

    #[test]
    fn registry_skips_disabled_laws() {
        let mut reg = ForceRegistry::new();
        reg.register(Box::new(TestLaw::new(false)));
        assert_eq!(reg.len(), 1);

        let mut bodies = RigidBodySet::new();
        let mut colliders = ColliderSet::new();
        let narrow_phase = NarrowPhase::new();
        let mut log: Vec<Option<BodyForceLog>> = Vec::new();
        let mut pending = SmallVec::new();
        let mut friction = Vec::new();
        let mut facade = make_facade(&mut bodies, &mut colliders, &narrow_phase, &mut log, &mut pending, &mut friction);

        reg.apply_at(0, &mut facade);
        let report = facade.drain_report();
        assert_eq!(report.max_reynolds_number, 0.0);
    }

    #[test]
    fn registry_unregister() {
        let mut reg = ForceRegistry::new();
        let h1 = reg.register(Box::new(TestLaw::new(true)));
        let h2 = reg.register(Box::new(TestLaw::new(true)));
        assert_eq!(reg.len(), 2);

        assert!(reg.unregister(h1));
        assert_eq!(reg.len(), 1);
        assert!(!reg.unregister(h1));
        assert!(reg.get(h1).is_none());
        assert!(reg.get(h2).is_some());
    }

    #[test]
    fn registry_find_by_type() {
        let mut reg = ForceRegistry::new();
        let h1 = reg.register(Box::new(TestLaw::new(true)));
        let h2 = reg.register(Box::new(TestLaw::new(true)));
        let h3 = reg.register(Box::new(TestLaw::new(true)));

        let found = reg.find_by_type(ForceLawType::Custom(999));
        assert_eq!(found.len(), 3);
        assert!(found.contains(&h1));
        assert!(found.contains(&h2));
        assert!(found.contains(&h3));

        let not_found = reg.find_by_type(ForceLawType::AirDrag);
        assert!(not_found.is_empty());
    }

    #[test]
    fn registry_reuses_freed_slots() {
        let mut reg = ForceRegistry::new();
        let h1 = reg.register(Box::new(TestLaw::new(true)));
        let h2 = reg.register(Box::new(TestLaw::new(true)));
        assert!(reg.unregister(h1));
        assert!(reg.unregister(h2));
        assert!(reg.is_empty());

        let h3 = reg.register(Box::new(TestLaw::new(true)));
        assert_eq!(reg.len(), 1);
        assert!(reg.get(h3).is_some());
    }

    #[test]
    fn facade_add_force_and_report() {
        let mut bodies = RigidBodySet::new();
        let mut colliders = ColliderSet::new();
        let narrow_phase = NarrowPhase::new();
        let mut log: Vec<Option<BodyForceLog>> = Vec::new();

        // Insert a dynamic body
        let builder = RigidBodyBuilder::dynamic().translation(Vector::new(0.0, 0.0, 0.0));
        let handle = bodies.insert(builder.build());

        let mut pending = SmallVec::new();
        let mut friction = Vec::new();
        let mut facade = make_facade(&mut bodies, &mut colliders, &narrow_phase, &mut log, &mut pending, &mut friction);

        let force = Vector::new(10.0, 0.0, 0.0);
        assert!(facade.add_force(handle, force, ForceLawType::AirDrag));
        assert!(facade.add_force(handle, Vector::new(0.0, -50.0, 0.0), ForceLawType::PointGravity));

        let report = facade.drain_report();
        let drag = report.contributions.get(&ForceLawType::AirDrag).unwrap();
        assert_eq!(drag.body_count, 1);
        assert!((drag.total_force.x - 10.0).abs() < 1e-12);

        let grav = report.contributions.get(&ForceLawType::PointGravity).unwrap();
        assert_eq!(grav.body_count, 1);

        // Log should be empty after drain
        assert!(log.is_empty());
    }

    #[test]
    fn facade_skips_fixed_body() {
        let mut bodies = RigidBodySet::new();
        let mut colliders = ColliderSet::new();
        let narrow_phase = NarrowPhase::new();
        let mut log: Vec<Option<BodyForceLog>> = Vec::new();

        let builder = RigidBodyBuilder::fixed();
        let handle = bodies.insert(builder.build());

        let mut pending = SmallVec::new();
        let mut friction = Vec::new();
        let mut facade = make_facade(&mut bodies, &mut colliders, &narrow_phase, &mut log, &mut pending, &mut friction);
        assert!(facade.add_force(handle, Vector::new(10.0, 0.0, 0.0), ForceLawType::AirDrag));

        let report = facade.drain_report();
        assert!(report.contributions.is_empty());
    }

    #[test]
    fn force_report_to_legacy_conversion() {
        let mut report = ForceReport::default();
        report.add(
            ForceLawType::AirDrag,
            crate::rapier::ffi::vec3_to_rapier(crate::rapier::ffi::Vec3 {
                x: -10.0,
                y: 0.0,
                z: 0.0,
            }),
            3,
        );
        report.add(
            ForceLawType::PointGravity,
            crate::rapier::ffi::vec3_to_rapier(crate::rapier::ffi::Vec3 {
                x: 0.0,
                y: -50.0,
                z: 0.0,
            }),
            1,
        );

        let legacy = report.to_legacy_report();
        assert_eq!(legacy.drag_body_count, 3);
        assert_eq!(legacy.total_drag_force.x, -10.0);
        assert!(legacy.total_external_force.x == -10.0);
    }
}
